apiVersion: v1
kind: Service
metadata:
  name: springboot-cd
spec:
  type: NodePort
  selector:
    app: springboot-cd
  ports:
    - protocol: TCP
      port: 9090          
      targetPort: 8080   
      nodePort: 31800    

  
